export const LOCATIONS = [
  {
    id: 'hus',
    name: 'Gammelt hus',
    description: 'Et slitent lite hus med lekkende tak og ødelagt gjerde. Ikke mye, men det er ditt!',
    color: '#8B6914',
    bgColor: '#2d5a27',
    startGold: 50,
    startFood: 10,
    difficulty: 'Lett',
    emoji: '🏚️',
  },
  {
    id: 'hule',
    name: 'Mørk hule',
    description: 'En romslig hule i fjellsiden. Trygg mot vær og vind, men du må bygge alt fra bunnen.',
    color: '#555566',
    bgColor: '#1a2a1a',
    startGold: 30,
    startFood: 5,
    difficulty: 'Vanskelig',
    emoji: '🕳️',
  },
  {
    id: 'landsby',
    name: 'Liten landsby',
    description: 'En falleferdig landsby med noen tomme hus. Naboene kan hjelpe — hvis du hjelper dem først.',
    color: '#a0522d',
    bgColor: '#3a5a2a',
    startGold: 40,
    startFood: 15,
    difficulty: 'Middels',
    emoji: '🏘️',
  },
  {
    id: 'skog',
    name: 'Skogens hjerte',
    description: 'Midt i en tett skog. Massevis av ressurser rundt deg, men ville dyr lurer i mørket.',
    color: '#2d6a1f',
    bgColor: '#0d2a0d',
    startGold: 20,
    startFood: 20,
    difficulty: 'Ekspert',
    emoji: '🌲',
  },
];
